### PR TITLE
fix welcome content not centered

### PR DESCRIPTION
**Pull request by StrayCodeOTM**
removed the attributes: `width: auto; text-align: left;` for make the content of welcome form centered and add in `#acp, #forumtable, p, td, th` to maintain alignment in the login form

### CODE REVIEW

**Comment by vendethiel** [comment]
Just as a heads up: there's no need to open a new pull request, github picks up the changes automatically :)

**Comment by StrayCodeOTM** [comment]
oh sorry, I'm new in the field ;)

**Comment by StrayCodeOTM** [comment]
i revert the commits because if i delete the attributes for centered the content in welcome form this influences other form and for example the login form in login_ip.php aren't no longer aligned. Is necessary another solution

**Comment by MWE001** [comment]
custom css entries is the ticket to fix these issues. The more css we can use and the less hard code, I think it is much better.

**Comment by MightyGorgon** [comment]
Please let me know if I can help with this...

**Comment by MightyGorgon** [comment]
Pull Request suspended... should you need to commit, please open a new one!

**Pull request closed without merging**
