### PR TITLE
Strict SQL install procedure

### PR DESCRIPTION
**Pull request by vendethiel**
- Make sure indexes aren't too long (at most 190 or 191)
- Make sure date values aren't created with a string value

### CODE REVIEW

**Comment by vendethiel** [comment]
This is necessary for MySQL 8+ and MariaDB 10+ in Strict SQL mode.

We can also decide **not** to alter the fields, but to alter index length instead. I don't think it matters much.

**Comment by MightyGorgon** [comment]
Hi,
can you please also create all ALTER TABLE commands so I can merge?

Example:
ALTER TABLE `phpbb_config` CHANGE `config_name` `config_name` VARCHAR(190) NOT NULL;

This is needed for updating existing DB.

**Review by MightyGorgon — APPROVED** [review]
I thought I already approved this PR... all changes are already included in my code.

**Comment by vendethiel** [comment]
I think the merge didn't completely work... For example this is obviously a bug: https://github.com/MightyGorgon/icy_phoenix/blob/37c6b1595d9df8809e1e6c8933045abcd336e0c4/templates/common/js/ajax_post.js#L39

**Pull request merged**
