### PR TITLE
Recurring first post

### LINKED ISSUE #91: Show first topic post on every page
Some forums like IPB, VB (and now a phpBB3.1 extension) allow you to show the first post of the topic on every page.
This is very useful for KB-style forums, for announcements, and for some others. I'd like to have this, at this point, as a per-forum option.

Thoughts?

### PR DESCRIPTION
**Pull request by vendethiel**
This adds the "show first post on every topic page" feature.

resolves #91

### CODE REVIEW

**Comment by vendethiel** [comment]
This should be fine.

**Comment by vendethiel** [comment]
Just pushed a new commit with the merge conflict fixed!

**Comment by vendethiel** [comment]
@MightyGorgon ?

**Comment by MightyGorgon** [comment]
I'll work on it in the next few days... just wait a bit more. :-)

**Comment by MightyGorgon** [comment]
I have applied the edits on my working tree... I'll merge with my commits.

**Pull request closed without merging**
